name: CatLoaf Poster

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  poster:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ai-bakery

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Image Generator
        run: python image_generator.py

      - name: Run Main
        run: python -u main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Run Poster
        run: python -u poster.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
